### PR TITLE
Add support to version 4 + all previous NBS versions

### PR DESCRIPTION
**Pull request by Bentroen**
### Overview
This PR updates `pynbs` to add support to the latest NBS version (version 4), as well as versions 1 and 2, which were previously unsupported.

It also adds the option to save a file in any of the older versions, for extended compatibility with older versions of Note Block Studio and other tools.

### Changes
- A `CURRENT_NBS_VERSION` constant was added to allow for easier updating in case of a new format release.
- The parser is version-agnostic, it will parse any file by detecting its version during read.
- The writer requires a version to be specified. The `File.save()` method from which it's called has had an optional `version` argument added to it which, if omitted, defaults to `CURRENT_NBS_VERSION`.
- Provided default values for variables that aren't present in certain versions. All `File` objects have all the attributes present in the latest NBS version; however, some of them may be set to default values when loading from older versions, or discarded as needed when saving in older versions.
- The `Note` class was subclassed from `namedtuple`, as `Layer` had been before. That is to provide default values when some parameters are not specified upon creating those objects.
  - For example, it's now possible to create a `Note` object by specifying only its tick, layer, key and instrument -- velocity, panning and pitch will default to their usual values. This avoids having to specify every property everytime.

### Design considerations
- While the version is more pertinent to the file on disk, and less to the song object, it was kept as a header attribute so it's still possible to query which version a song was saved in. However, changing this attribute has no effect on which version the song will be saved in -- the proper way to save a file in an older version is by explicitly passing the `version` argument in the `File.save()` method. The actual value written to the file is overriden with this value at save time.
- In the NBS specification, note block and layer panning are stored as an unsigned short ranging from 0-200, due to the inability of using signed values at the time. However, in a later update the pitch was stored as a _signed_ short -- it's the only field in the whole specification that "breaks the rule". This inconsistency in the signedness of the panning and pitch values (when a signed value would have made sense for both) is considered a mistake in Open Note Block Studio's design. The package makes up for it by subtracting 100 from the panning (or adding 100 when saving) to use the range `(-100, 100)`, which is more intuitive.
- Although classic `.nbs` files may contain either 5 or 10 default instruments, the fallback value was set to 10 since that's the value for the latest classic (pre-ONBS) release.
- Rather than adding a `self.version` method to the `Parser` and `Reader` classes, I decided to explicitly pass the version as an argument to each of the methods. This may look a bit unefficient, but explicit is better than implicit.
- I strived to avoid big structural changes, keeping mostly the same code structure as before. Further improvements can possibly be made in the future.

### CODE REVIEW

**Comment by vberlier** [comment]
I'm sooo bad at this, sorry for taking so long to reply... :grimacing:

Anyway, this is really good! I haven't been keeping up with Open Note Block Studio, but I only had to take care of a small typo and it worked out of the box. The backward compatibility is handled pretty nicely and the usability improvements to the `Note` class are welcome.

The way you're handling explicit modifications to the version header attribute is fine. I think transparently converting the range of the panning is nice. I'm also good with the way you're explicitly passing the version around.

I really appreciate the fact that you avoided substantial structural changes, it made it easier for me to review. But yeah I agree that there's a bunch of potential improvements to be done here. I wrote this such a long time ago. If you want I can add you as a contributor, you'd be welcome to help :+1:

**Comment by vberlier** [comment]
Alright, just released this in version 0.4.0.

**Comment by Bentroen** [comment]
Thanks a lot for reviewing the pull request!

Don't worry, I know you created this library as a one-off thing -- I also only used it to play around with .nbs files, not for any serious purpose. But, since then, I somehow became much more involved with the note block scene. Not only I became the primary developer of Open Note Block Studio, I'm also working in a cross-platform rewrite made entirely in Python. And rather than reinventing the wheel, I decided to use this library for handling the .nbs files, since it makes everything sooo much easier. Since it's gonna play a major role in the functionality of the new program, it's important to keep it up-to-date. With that in mind, being added as a contributor would be nice! This way I don't have to bother you everytime we do some change to the format. xD

**Comment by vberlier** [comment]
Duude I didn't even realize you were now the maintainer! That's amazing, congrats! I'll add you as a contributor right away :+1:

**Pull request merged**
